# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: "BrowserStack Env Setup"
      uses: "browserstack/github-actions/setup-env@master"
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        build-name: "BROWSERSTACK_BUILD_NAME"
        project-name: "TEST_PROJECT_NAME"
    - name: Run test
        id: test
        continue-on-error: true
        run: npm run bstack-parallel
      - run: npm run generateMochawesome
      - name: Archive mochawesome reports
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report/
